### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by JakubKepak** [chingu-voyages/v28-geckos-team-05#73]
**__Task Description__**
Create a signup page so users will be able to use features available only to authenticated users

**__Steps to Follow (optional)__**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**__Additional Considerations__**
N/a

**Comment by jdmedlock** [comment]
Some delay due to his job, but should still be able to complete by end of Sprint 3
